from enum import Enum

class DialogState(Enum):
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    READY_TO_RECOMMEND = "READY_TO_RECOMMEND"
    REFINING = "REFINING"
    COMPARING = "COMPARING"
    REFUSAL = "REFUSAL"
    SATISFIED = "SATISFIED"
